apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: godaddy-webhook-webhook-tls
  renewBefore: 240h
  dnsNames:
  - '<wildcard-dns-domain>'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
