apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: cnvrg
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: cnvrg-project-dataset-cache-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnvrg-project-dataset-cache-pvc
  namespace: cnvrg
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 4Tb
