apiVersion: batch/v1
kind: CronJob
metadata:
  name: metagpu-job
  namespace: cnvrg
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      name: metagpu-job
    spec:
      template:
        spec:
          containers:
          - name: metagpu-job
            image: docker.io/bsoper/kubectl-job:1.0.0
            imagePullPolicy: Always
            command:
              - /bin/sh
              - -c
              - |
                kubectl -n cnvrg patch ds metagpu-device-plugin -p '{"spec": {"template": {"spec": {"nodeSelector": null }}}}'
                kubectl -n cnvrg patch ds metagpu-device-plugin -p '{"spec": {"template": {"spec": {"nodeSelector": {"metagpu": "present"}}}}}'
          restartPolicy: Never
          serviceAccountName: cnvrg-control-plane
